### PR TITLE
add symlink to host icc profiles

### LINKED ISSUE #11: You can not select icc profile.
The icc profile can not be selected.
The predefined path is `/usr/share/color/icc` and flatpak can not access that directory.
The new path is `/run/host/usr/share/color/icc`

Actually, no application can see icc profiles.

### PR DESCRIPTION
**Pull request by eszlari**
fixes #11

### CODE REVIEW

**Comment by hfiguiere** [comment]
I'd rather see this part of the `post-install`

**Comment by eszlari** [comment]
Why?

**Comment by hfiguiere** [comment]
because it's more logical. It's not a source file nor needed to build.

**Comment by eszlari** [comment]
This doesn't depend on the build being finished, so `post-install` is not logical either.

I moved it to `cleanup-commands`.

**Comment by hfiguiere** [comment]
but it is about making the app functional after building. That's were we create the directory for extension point (if any). I don't think "cleanup command" is logical either.

**Comment by eszlari** [comment]
I like to avoid putting things needlessly in `post-install`, because it wastes time, when you want to test a change that doesn't require a rebuild and it gets rebuilt anyway.

**Comment by hfiguiere** [comment]
Since the change is tested then it's fine. I don't think this belong to the cleanup phase.

**Pull request closed without merging**
