### PR TITLE
Bump to 1.0.1

### PR DESCRIPTION
**Pull request by linkmauve**
Inkscape 1.0.1 just got released, see https://inkscape.org/release/inkscape-1.0.1/

The appdata patch apparently got applied upstream, so we don’t have to carry it any more.

### CODE REVIEW

**Comment by hfiguiere** [comment]
Yeah I took care of submitting the appdata as it went.

**Comment by linkmauve** [comment]
Apparently it’s still broken though, for some reason… https://flathub.org/builds/#/builders/28/builds/3162

**Comment by hfiguiere** [comment]
> Apparently it’s still broken though, for some reason… https://flathub.org/builds/#/builders/28/builds/3162

that mean it has two releases with the same version in it.

**Comment by cho2** [comment]
```
org.inkscape.Inkscape:             AppData problem: tag-invalid : <release> version was duplicated
Error loading AppData file: AppData file /app/share/appdata/org.inkscape.Inkscape.appdata.xml was not valid
```

it's upstream problem

```
    <release version="1.0" date="2020-09-07">
      <description>
        <p>Inkscape 1.0.1</p>
```

**Comment by hfiguiere** [comment]
> ```
> org.inkscape.Inkscape:             AppData problem: tag-invalid : <release> version was duplicated
> Error loading AppData file: AppData file /app/share/appdata/org.inkscape.Inkscape.appdata.xml was not valid
> ```
> 
> it's upstream problem
> 
> ```
>     <release version="1.0" date="2020-09-07">
>       <description>
>         <p>Inkscape 1.0.1</p>
> ```

Yup. I hadn't checked the tarball yet. Will submit a Merge Request.

**Comment by cho2** [comment]
I try to fix it https://github.com/flathub/org.inkscape.Inkscape/pull/62

**Comment by linkmauve** [comment]
Looks fine to me! @hfiguiere if you want to test too, I consider this PR ready. :)

**Comment by hfiguiere** [comment]
Thanks !

**Comment by linkmauve** [comment]
Is it normal that https://flathub.org/apps/details/org.inkscape.Inkscape still shows 1.0?

**Comment by cho2** [comment]
@linkmauve should be 1.0.1.

I checked `org.inkscape.Inkscape.appdata.xml.in` in the tarball
https://github.com/flathub/org.inkscape.Inkscape/blob/d0f7eee72494d5fe9418d00893d65aff57219880/org.inkscape.Inkscape.json#L421  

It still 1.0 on `release version`

```
  <release version="1.0" date="2020-09-07">
      <description>
        <p>Inkscape 1.0.1</p>
```

**Comment by hfiguiere** [comment]
It shows 1.0.1 here. Not sure how long the website take to update.

Also when I installed even the test build `flatpak list` showed 1.0.1.

**Comment by hfiguiere** [comment]
> @linkmauve should be 1.0.1.
> 
> I checked `org.inkscape.Inkscape.appdata.xml.in` in the tarball
> 
> https://github.com/flathub/org.inkscape.Inkscape/blob/d0f7eee72494d5fe9418d00893d65aff57219880/org.inkscape.Inkscape.json#L421
> 
> It still 1.0 on `release version`

It is patched by the flatpak. 
See https://github.com/flathub/org.inkscape.Inkscape/pull/61/files#diff-0ecd6629ecd9ca1d1d5b581ab42490d1

The tarball has no reason to change.

**Comment by cho2** [comment]
> It shows 1.0.1 here. Not sure how long the website take to update.

I recheck again and show 1.0.1.

> The tarball has no reason to change.

https://gitlab.com/inkscape/inkscape/-/merge_requests/2304/diffs
I thought that it will rebuild

**Comment by hfiguiere** [comment]
One doesn't simply redo a tarball without changing the version.

**Pull request merged**
