### PR TITLE
Build 1.0-beta1

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thanks for looking into this. It seems that the appdata is invalid.

**Comment by hfiguiere** [comment]
Probably needs a new patch.

If only when using flatpak-builder we'd get that validation, it would save a lot of time.

(local build is already quite long)

**Comment by matze** [comment]
Great, works like a charm! I guess it would be a good idea if you could open an upstream PR about the appdata validation.

**Comment by hfiguiere** [comment]
MR submitted upstream https://gitlab.com/inkscape/inkscape/merge_requests/897

**Pull request merged**
