### PR TITLE
add global menu support

### PR DESCRIPTION
**Pull request by cho2**
add global menu support

### CODE REVIEW

**Comment by cho2** [comment]
```
flatpak run org.inkscape.Inkscape 
Gtk-Message: 07:01:48.123: Failed to load module "atk-bridge"
Gtk-Message: 07:01:48.127: Failed to load module "appmenu-gtk-module"
```

**Comment by hfiguiere** [comment]
The proper question is does it work? Remember that Inkscape 0.95.x uses Gtk2.

**Comment by cho2** [comment]
It's not working. I closed this PR.

**Comment by hfiguiere** [comment]
maybe you want to try with the beta branch? It uses Gtk3.

**Comment by cho2** [comment]
I'll take a look

**Pull request closed without merging**
