### PR TITLE
Bump dependencies to their latest version

### PR DESCRIPTION
**Pull request by linkmauve**
I also dropped libsigc++ 3.0 which isn’t used yet.

### CODE REVIEW

**Comment by nedrichards** [comment]
Whilst we're at this point in time we'll need a mirror PR that also applies changes to the beta branch, otherwise this sort of thing will get dropped.

**Comment by hfiguiere** [comment]
Poppler no longer uses autotools to build.

**Comment by hfiguiere** [comment]
> Whilst we're at this point in time we'll need a mirror PR that also applies changes to the beta branch, otherwise this sort of thing will get dropped.

My plan when a new beta happen is to merge master back to beta and add the beta version.

**Comment by linkmauve** [comment]
Hmm, now that poppler is fixed, the issue is numpy.

**Comment by hfiguiere** [comment]
I suggest reverting the python module upgrades and move on. It fails locally here.

**Comment by hfiguiere** [comment]
I meant the one for numpy. Unless you have a solution.

**Comment by linkmauve** [comment]
This should be good to go. :)

**Comment by hfiguiere** [comment]
Thank you !

**Comment by linkmauve** [comment]
Fyi, Inkscape is now linking to Flathub for this package: https://inkscape.org/release/1.0/gnulinux/

**Pull request merged**
