### PR TITLE
README: Add permissions rationale

### PR DESCRIPTION
**Pull request by travier**
JSON does not support comments well thus move those to the README.

### CODE REVIEW

**Comment by travier** [comment]
Does Inkscape really need full host filesystem acces? Probably for exports?

**Comment by hfiguiere** [comment]
I would say it doesn't but then downgrading permissions break for users.

(I'm not the original maintainer)

**Comment by travier** [comment]
Note that this PR does not touch the permissions. I'm just asking to update the README with the info.

**Comment by hfiguiere** [comment]
yeah I was just explaining my position on this. Also it should be noted why `--socket=x11` is   there too: https://github.com/flathub/org.inkscape.Inkscape/issues/101

**Comment by travier** [comment]
Replaced by https://github.com/flathub/org.inkscape.Inkscape/pull/129

**Pull request closed without merging**
