### PR TITLE
beta: Add 1.2

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by hfiguiere** [comment]
it works, but flatpak list still shows the version is 1.1 as the appstream file isn't updated.

**Comment by cho2** [comment]
I'm curious because on org.inkscape.Inkscape.appdata.xml.in line 44, it's already has `<release version="1.2-beta" date="2020-04-05">` :thinking:

**Comment by hfiguiere** [comment]
it should actually have failed validation. but then look at the date. I know it still feel like we are in 2020.

**Comment by cho2** [comment]
wrong year

**Comment by cho2** [comment]
```
Inkscape                                           org.inkscape.Inkscape                                            1.2-beta                         test                   inkscape-origin             user
```

**Pull request merged**
