### PR TITLE
Update to 1.0.1

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
bot, build org.inkscape.Inkscape

**Comment by cho2** [comment]
```
error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zwnx3rxe/overlay --no-warn-script-location --no-binary :all: --only-binary :none: --no-index --find-links file:///run/build/python3-numpy -- 'setuptools!=49.2.0' wheel 'Cython>=0.29.21'
       cwd: None
  Complete output (4 lines):
  Looking in links: file:///run/build/python3-numpy
  Collecting setuptools!=49.2.0
    ERROR: Could not find a version that satisfies the requirement setuptools!=49.2.0 (from versions: none)
  ERROR: No matching distribution found for setuptools!=49.2.0
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zwnx3rxe/overlay --no-warn-script-location --no-binary :all: --only-binary :none: --no-index --find-links file:///run/build/python3-numpy -- 'setuptools!=49.2.0' wheel 'Cython>=0.29.21' Check the logs for full command output.
```

**Comment by hfiguiere** [comment]
I was getting this locally even when building #61

**Comment by cho2** [comment]
bot, build org.inkscape.Inkscape

**Comment by cho2** [comment]
```
ninja: build stopped: subcommand failed.
]2;flatpak-builder: Cleanup inkscapeError: module inkscape: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-dyIEg7
```

**Comment by cho2** [comment]
LGTM

Cuplikan layar dari 2020-09-08 12-33-15

**Comment by linkmauve** [comment]
Hi, this patch (plus others) have now been [merged upstream](https://gitlab.com/inkscape/inkscape/-/commits/1.0.x), I include them in #61.

In addition, I bumped the version of all dependencies to their latest stable, and simplified Python packages.

**Comment by cho2** [comment]
@linkmauve Great, thanks! We can continue in #61

**Pull request closed without merging**
