### PR TITLE
Update ghostscript to 9.25

### PR DESCRIPTION
**Pull request by Erick555**
This is another urgent security update of ghostscript, more info at https://www.ghostscript.com/doc/9.25/News.htm

### CODE REVIEW

**Comment by matze** [comment]
Thanks, could you squash those commits to a single one?

**Comment by Erick555** [comment]
You can squash them while merging.

**Comment by matze** [comment]
bot, build

**Comment by matze** [comment]
> You can squash them while merging.

Yes, I can and did. But it sucks to edit commit messages from the Github editor (which we all know does not respect the commit message guidelines).

**Pull request merged**
