### PR TITLE
Update stable to Inkscape 1.0

### LINKED ISSUE #3: Add UniConvertor
Without it Inkscape cannot open `.cdr` files.

This is the message I get when I try to open one:

```
You need to install the UniConvertor software.
For GNU/Linux: install the package python-uniconvertor.
For Windows: download it from
https://sk1project.net/modules.php?name=Products&product=uniconvertor&op=download
and install into your Inkscape's Python location
```

### LINKED ISSUE #22: unable to print
inkscape as flatpak doesn't list any of my printers

### LINKED ISSUE #36: Inkscape is using fallback GTK theme
Hi, I have Arch Linux and use Gnome 3.32. I've just installed Inkscape from Flathub and for some reason, its version of Inkscape looks pretty ugly:
image
I've tried running it from command line and I only see this single error:
```
Gtk-Message: 15:33:30.880: Failed to load module "canberra-gtk-module"
```
Is this an issue with the package itself or do I just have something missing on my system?

### PR DESCRIPTION
**Pull request by hfiguiere**
I updated the `beta` branch to 1.0 (PR to come) and merge it with master to get 1.0 on `stable`.

The appdata patch will be submitted upstream.

- Closes #36 
- Closes #22
- Closes #3

### CODE REVIEW

**Comment by hfiguiere** [comment]
Looks like the tarball changed... Let me check this.

**Comment by hfiguiere** [comment]
The tarball URL changed and the new one timeout. Wait for an update with an updated manifest.

**Comment by TingPing** [comment]
This fails to build btw: https://flathub.org/builds/#/builders/8/builds/2310

**Comment by hfiguiere** [comment]
> This fails to build btw: https://flathub.org/builds/#/builders/8/builds/2310

The failure above is for #55

**Pull request merged**
