### PR TITLE
beta: Add 1.1-beta1

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
cc @linkmauve @hfiguiere

**Comment by linkmauve** [comment]
Seems to work fine, thanks!

There is only a tiny issue I could find on cursory testing, the license file is looked for in `/app/share/inkscape/doc/LICENSE` in Help > About Inkscape, but isn’t found. You may want to symlink it there.

**Comment by cho2** [comment]
Cuplikan layar dari 2021-03-31 19-22-21

LGTM

**Comment by cho2** [comment]
I'm thinking of updating runtime to GNOME 40 for 1.1-beta1, just wait and see  #74

**Review by linkmauve — APPROVED** [review]
LGTM too, but note that #74 targets master and not beta, so it will need the same changes here.

**Comment by hfiguiere** [comment]
> LGTM too, but note that #74 targets master and not beta, so it will need the same changes here.

just go ahead with this for now. The Gnome 40 update was more complicated than I wished it was.

FWIW Gimp has similar issues...

**Comment by cho2** [comment]
Noted. Stay with 3.36 runtime. Feel free to merge.

**Comment by hfiguiere** [comment]
Thanks!

**Pull request merged**
