### PR TITLE
Update runtime to Gnome 43

### PR DESCRIPTION
**Pull request by skierpage**
If this triggers a build, I'll test it.

### CODE REVIEW

**Comment by cho2** [comment]
```
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 602, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
          self._add_defaults_build_sub_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
          self.filelist.extend(chain.from_iterable(files))
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 507, in extend
          self.files.extend(filter(self._safe_path, paths))
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
          files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
          cmds = (self.get_finalized_command(c) for c in missing_cmds)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/run/build/python3-numpy/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
          v = getattr(c, a)
        File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
          return _build_ext.build_ext.__getattr__(self, name)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: fcompiler. Did you mean: 'compiler'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
[?25hFB: host_command_exited_cb 4000948 256
]2;flatpak-builder: Cleanup python3-numpyError: module python3-numpy: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-4/build/.flatpak-builder/rofiles/rofiles-XS3JM6
program finished with exit code 1
elapsedTime=1104.718622
```

**Comment by skierpage** [comment]
> ```
> ...
>         File "/run/build/python3-numpy/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
> ...
>       [end of output]

So it seems to be failing while "Processing /run/build/python3-numpy". I have no idea what's going on, I didn't put "fcompile" anywhere.

**Comment by cho2** [comment]
@hfiguiere any hints?

**Comment by skierpage** [comment]
The commit that #141 references is better.

**Pull request closed without merging**
