### PR TITLE
rebase on gnome-platform 3.28

### PR DESCRIPTION
**Pull request by joergister**
worked in my local builds

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by joergister** [comment]
I honestly don't know how to fix this. 
I just tried it on my local machine because I was curious if it would work and it did work so I opened a PR.
Maybe someone can help out? 
Otherwise I would just close this PR.

**Comment by matze** [comment]
Sorry, I already merged the bump to 3.28 because I haven't seen the PR … Of course, I also hit the failure with aarch64. The problem is that there is no NEON support on aarch64 and ghostscript compiles its own libpng with it. As of now, I don't see how we can pass `--enable-arm-neon=no` to libpng or disable building libpng at all. I will try to fix this.

**Comment by joergister** [comment]
Oh nice to hear it was rebased. 
Good luck solving this problem

**Comment by matze** [comment]
It [went fine](https://flathub.org/builds/#/builders/2/builds/2769) this afternoon after I used the same build description for ghostscript as GIMP.

**Comment by joergister** [comment]
Glad to hear that.

**Pull request closed without merging**
